name: test
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up dump action
        uses: DailyVanity/Dump-MySQL@master
        with:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          S3_PATH: ${{ secrets.S3_PATH }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          NAME: "github_test"
          